apiVersion: apps/v1
kind: Deployment
metadata:
 name: apps-1
spec:
 replicas: 2
 selector:
  matchLabels:
   app: app-1
 template:
  metadata:
   labels:
    app: app-1
  spec:
   containers:
   - name: app-1
     image: ajayvallala/app-1:v1

---

apiVersion: v1
kind: Service
metadata:
 name: app1-service
spec:
 selector:
  app: app-1
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
   alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
   alb.ingress.kubernetes.io/scheme: internet-facing
   alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:448049818055:certificate/c1a18e40-506c-405e-af64-c4d8f17a1752
   alb.ingress.kubernetes.io/target-type: ip
   alb.ingress.kubernetes.io/group.name: vallalastore
spec:
  ingressClassName: alb
  rules:
  - host: "app1.vallalas.store"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1-service
            port:
              number: 80

