apiVersion: apps/v1
kind: Deployment
metadata:
 name: apps-1
spec:
 replicas: 2
 selector:
  matchLabels:
   app: app-1
 template:
  metadata:
   labels:
    app: app-1
  spec:
   containers:
   - name: app-1
     image: ajavallala/app1:v1

---

apiVersion: v1
kind: Service
metadata:
 name: app1-service
spec:
 selector:
  app: app-1
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
   alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
   alb.ingress.kubernetes.io/frontend-nlb-scheme:  internet-facing
   alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:448049818055:certificate/68bea515-6649-45f6-be0a-99dd47b84e94
   alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: service1
            port:
              number: 80
  - host: "*.foo.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
